services:
  prefect:
    build: .
    container_name: prefect
    env_file:
      - .env
    command: >
      bash -c "
        prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api &&
        prefect server start --host 0.0.0.0 --port 4200 & 
        sleep 30 &&
        cd /app/sports &&
        prefect deploy --prefect-file prefect.yaml
      "
    ports:
      - "4200:4200"
    volumes:
      - prefect_home:/root/.prefect
    restart: unless-stopped

volumes:
  prefect_home: