version: "3.9"

services:
  prefect:
    build: .
    env_file:
      - .env
    container_name: prefect
    command: >
      bash -c "
        prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api &&
        prefect server start --host 0.0.0.0 --port 4200 &
        sleep 30 &&
        prefect worker start --pool docker-agent-pool
      "
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    volumes:
      - prefect_home:/root/.prefect
    restart: unless-stopped

volumes:
  prefect_home: